services:
  furnix-backend:
    build: .
    container_name: furnix-backend
    restart: always
    ports:
      - "7778:7777"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: ["node", "dist/server.js"]
    extra_hosts:
      - "host.docker.internal:host-gateway"